//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBIoT.GUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PBIoTDBEntities : DbContext
    {
        public PBIoTDBEntities()
            : base("name=PBIoTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<uspObtenerVariablePLCGraficaXMinuto_Result> uspObtenerVariablePLCGraficaXMinuto(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspObtenerVariablePLCGraficaXMinuto_Result>("uspObtenerVariablePLCGraficaXMinuto", fechaParameter);
        }
    
        public virtual ObjectResult<uspObtenerVariablesOeeHora_Result> uspObtenerVariablesOeeHora(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspObtenerVariablesOeeHora_Result>("uspObtenerVariablesOeeHora", fechaParameter);
        }
    
        public virtual ObjectResult<uspObtenerOEEXHora_Result> uspObtenerOEEXHora(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspObtenerOEEXHora_Result>("uspObtenerOEEXHora", fechaParameter);
        }
    
        public virtual int uspGuardarParoPendientePorFinalizar(Nullable<long> idParo, string motivo)
        {
            var idParoParameter = idParo.HasValue ?
                new ObjectParameter("IdParo", idParo) :
                new ObjectParameter("IdParo", typeof(long));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("Motivo", motivo) :
                new ObjectParameter("Motivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspGuardarParoPendientePorFinalizar", idParoParameter, motivoParameter);
        }
    
        public virtual ObjectResult<uspObtenerParoPorFinalizar_Result> uspObtenerParoPorFinalizar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspObtenerParoPorFinalizar_Result>("uspObtenerParoPorFinalizar");
        }
    
        public virtual ObjectResult<uspObtenerInformacionParosXDia_Result> uspObtenerInformacionParosXDia(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspObtenerInformacionParosXDia_Result>("uspObtenerInformacionParosXDia", fechaParameter);
        }
    
        public virtual ObjectResult<uspObtenerTop5ParosXDia_Result> uspObtenerTop5ParosXDia(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspObtenerTop5ParosXDia_Result>("uspObtenerTop5ParosXDia", fechaParameter);
        }
    
        public virtual int uspActualizarMotivoParo(Nullable<long> idParo, string motivo)
        {
            var idParoParameter = idParo.HasValue ?
                new ObjectParameter("IdParo", idParo) :
                new ObjectParameter("IdParo", typeof(long));
    
            var motivoParameter = motivo != null ?
                new ObjectParameter("Motivo", motivo) :
                new ObjectParameter("Motivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("uspActualizarMotivoParo", idParoParameter, motivoParameter);
        }
    
        public virtual ObjectResult<uspObtenerParosMotivoXMes_Result> uspObtenerParosMotivoXMes(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspObtenerParosMotivoXMes_Result>("uspObtenerParosMotivoXMes", fechaParameter);
        }
    
        public virtual ObjectResult<uspObtenerTodosParosPendientesFinalizar_Result> uspObtenerTodosParosPendientesFinalizar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspObtenerTodosParosPendientesFinalizar_Result>("uspObtenerTodosParosPendientesFinalizar");
        }
    }
}
